### ISSUE TITLE
Build time environment variables leaking into run-time

### ISSUE THREAD

**Issue by caizixian** [mmtk/ci-perf-kit#30]
For example, the mutator perf [script](https://github.com/mmtk/ci-perf-kit/blob/abf041f/scripts/mutator-history-run.sh#L32) sets `MMTK_PLAN=semispace` during build time for the `make` [command](https://github.com/mmtk/mmtk-openjdk/blob/648bb27/openjdk/CompileThirdPartyHeap.gmk#L6) to set `--features` during compilation time.
This variable is not unset and results in confusing warning message [here](https://github.com/mmtk/ci-perf-result/blob/self-hosted/mutator/wrench-2021-08-20-Fri-195256/luindex.6000.132.jdk-mmtk-no-zeroing-nogc.ms.s.c2.tph.xmx8000M.xms8000M.rmmtkprobe.log.gz).

```
Warn: unable to set plan="semispace". Cant parse value. Default value will be used.
```

**Comment by qinsoon** [comment]
Fixed in 80e1696b9451843225ea316cf591e3fe64b36ecb. We always choose plan at run-time now.
