### ISSUE TITLE
Irrelevant "plan" parameter for build_openjdk_with_features

### ISSUE THREAD

**Issue by wks** [mmtk/ci-perf-kit#32]
Since https://github.com/mmtk/mmtk-core/commit/b721a6d29d736282c36aa01196efd8f5bf26567f, MMTk selects its plan at run time instead of compile time.

However, in `scripts/common.sh`, the `build_openjdk_with_features` function takes a `plan` parameter.  When this function is used, e.g. in `scripts/openjdk-compare.sh`, this function is called multiple time, passing a different plan each time.  This will waste time building multiple copies of OpenJDK with no difference except forcing a particular Plan (and the Plan is still selected by setting the `MMTK_PLAN` environment variable internally in `mmtk-openjdk/mmtk/src/lib.rs`).

This compile-time parameter should be removed, and tests should be run under different `MMTK_PLAN` environment variables.

**Comment by qinsoon** [comment]
Thanks for the issue. The current script does not support running different 'configs' with different env vars. I am migrating to the new running script which supports this, and I will remove the build time plan.

**Comment by qinsoon** [comment]
Done in 80e1696b9451843225ea316cf591e3fe64b36ecb.
