### ISSUE TITLE
Use product/image build instead of exploded image

### ISSUE THREAD

**Issue by k-sareen** [mmtk/ci-perf-kit#35]
Currently the build scripts seem to use the exploded image. We have known that it's not wise to use the exploded image for benchmarking. From memory we were planning on having a clean start for our benchmarking results. It would be good if we can move to a product/image build then as well.

Edit: This is for the OpenJDK build only.

**Comment by qinsoon** [comment]
Done in 80e1696b9451843225ea316cf591e3fe64b36ecb.
